# Generated by Django 5.0.3 on 2024-03-07 14:35

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('banner', models.ImageField(default='user_banner.jpg', upload_to='user_banner/')),
                ('profile_picture', models.ImageField(default='user_banner.jpg', upload_to='user_banner/')),
                ('joining_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('biography', models.TextField(blank=True, default=None, max_length=100, null=True)),
                ('location', models.TextField(blank=True, default=None, max_length=200, null=True)),
                ('is_private', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
