# Generated by Django 5.0.3 on 2024-03-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='private',
            new_name='is_private',
        ),
    ]
